export const adminUser = {
  name: 'main admin',
  email: 'admin@hpdc.local',
  role: 'Admin',
  avatar: '/assets/admin-avatar.svg',
};

export const adminStats = [
  {
    id: 'total-applications',
    label: 'Total Applications',
    value: 145,
    icon: 'ClipboardList',
    color: 'green',
  },
  {
    id: 'scheduled-applications',
    label: 'Scheduled Application',
    value: 24,
    icon: 'ClipboardCheck',
    color: 'amber',
  },
  {
    id: 'active-certificates',
    label: 'Active Certificates',
    value: 36,
    icon: 'Award',
    color: 'green',
  },
  {
    id: 'withdrawn-certificates',
    label: 'Withdrawn Certificates',
    value: 1,
    icon: 'FileX',
    color: 'red',
  },
  {
    id: 'suspended-certificates',
    label: 'Suspended Certificates',
    value: 7,
    icon: 'FileWarning',
    color: 'amber',
  },
];

export const adminRecentApplications = [
  {
    id: 'APP-2026-0167',
    applicationNo: 'APP-2026-0167',
    companyName: 'AL submission CO. LTD',
    status: 'Assessment Schedule',
    reviewers: [
      { initials: 'C', color: 'bg-emerald-100 text-emerald-800' },
      { initials: 'TC', color: 'bg-teal-100 text-teal-800' },
      { initials: '+2', color: 'bg-[#1B4332] text-white' },
    ],
  },
  {
    id: 'APP-2026-0159',
    applicationNo: 'APP-2026-0159',
    companyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    status: 'Assessment Schedule',
    reviewers: [
      { initials: 'C', color: 'bg-emerald-100 text-emerald-800' },
      { initials: 'W', color: 'bg-blue-100 text-blue-800' },
      { initials: 'TC', color: 'bg-teal-100 text-teal-800' },
    ],
  },
  {
    id: 'APP-2026-0166',
    applicationNo: 'APP-2026-0166',
    companyName: 'AL FRESH CO. LTD',
    status: 'Rejected',
    reviewers: [],
  },
  {
    id: 'APP-2026-0165',
    applicationNo: 'APP-2026-0165',
    companyName: 'foods&drink',
    status: 'Approved',
    reviewers: [
      { initials: 'C', color: 'bg-emerald-100 text-emerald-800' },
      { initials: 'TC', color: 'bg-teal-100 text-teal-800' },
    ],
  },
  {
    id: 'APP-2026-0144',
    applicationNo: 'APP-2026-0144',
    companyName: 'Hello',
    status: 'Approved',
    reviewers: [],
  },
];

export const adminUsers = {
  company: [
    {
      id: '1',
      company: "food's ...",
      contactPerson: 'dua afaz',
      email: 'dua...',
      registrationNo: '12345678910',
      sector: 'sector38',
      country: 'pakistan',
      phone: '+927647863878',
    },
    {
      id: '2',
      company: 'Ayesha...',
      contactPerson: 'Ayesha',
      email: 'aye...',
      registrationNo: '56377253',
      sector: 'Hr',
      country: 'Pakistan',
      phone: '+92258',
    },
    {
      id: '3',
      company: 'enuofqw',
      contactPerson: 'dcrewcw',
      email: 'ajc...',
      registrationNo: '43432443243243',
      sector: 'nicoac',
      country: 'ecsds',
      phone: '+475',
    },
    {
      id: '4',
      company: 'asdds',
      contactPerson: 'fafafafa',
      email: 'cav...',
      registrationNo: '543567755434546',
      sector: 'sadsdada',
      country: 'grzgrgsf',
      phone: '+923254635768',
    },
    {
      id: '5',
      company: 'Fjejcnds',
      contactPerson: 'Djsjcje',
      email: 'nds...',
      registrationNo: '37371838543',
      sector: 'Fndj',
      country: 'Dnsjcj',
      phone: '+923492881995',
    },
    {
      id: '6',
      company: 'mishal ....',
      contactPerson: 'Dua Ansari',
      email: 'hafi...',
      registrationNo: '456',
      sector: 'sector',
      country: 'pakista',
      phone: '+927676',
    },
    {
      id: '7',
      company: 'ronin',
      contactPerson: 'FATIMA',
      email: 'roni...',
      registrationNo: '23456787654567898764567',
      sector: 'main secto',
      country: 'UAE',
      phone: '+923887',
    },
  ],
  consultant: [
    {
      id: '101',
      company: 'Global ESG Advisors',
      contactPerson: 'Tariq Mansoor',
      email: 'tariq@esgadvisors.com',
      registrationNo: 'CONS-9021',
      sector: 'Consulting',
      country: 'Saudi Arabia',
      phone: '+966543219876',
    },
    {
      id: '102',
      company: 'Green Audit Partners',
      contactPerson: 'Layla Al-Harbi',
      email: 'layla@greenaudit.sa',
      registrationNo: 'CONS-8834',
      sector: 'Environmental',
      country: 'Saudi Arabia',
      phone: '+966512345678',
    },
  ],
  admin: [
    {
      id: '201',
      company: 'HPDC Authority',
      contactPerson: 'main admin',
      email: 'admin@hpdc.local',
      registrationNo: 'ADMIN-001',
      sector: 'Governance',
      country: 'Saudi Arabia',
      phone: '+966112233445',
    },
    {
      id: '202',
      company: 'HPDC Tech Ops',
      contactPerson: 'System Administrator',
      email: 'ops@hpdc.local',
      registrationNo: 'ADMIN-002',
      sector: 'Technology',
      country: 'Saudi Arabia',
      phone: '+966112233446',
    },
  ],
};

export const adminApplications = [
  {
    id: '1',
    applicationNo: 'APP-2026-0167',
    companyName: 'AL sub...',
    fullCompanyName: 'AL submission CO. LTD',
    reviewers: [
      { initials: 'C', color: 'bg-emerald-100 text-emerald-800' },
      { initials: 'TC', color: 'bg-teal-100 text-teal-800' },
      { initials: '+2', color: 'bg-[#1B4332] text-white' },
    ],
    contact: '+927...',
    status: 'Assessment Schedule',
    submittedDate: '2026-09-03',
    documentsCount: 4,
    hasUpdateAction: true,
  },
  {
    id: '2',
    applicationNo: 'APP-2026-0166',
    companyName: 'AL FRE...',
    fullCompanyName: 'AL FRESH CO. LTD',
    reviewers: [],
    contact: '+927...',
    status: 'Rejected',
    submittedDate: '2026-09-03',
    documentsCount: 2,
    hasUpdateAction: false,
  },
  {
    id: '3',
    applicationNo: 'APP-2026-0165',
    companyName: 'foods&...',
    fullCompanyName: 'foods&drink',
    reviewers: [
      { initials: 'C', color: 'bg-emerald-100 text-emerald-800' },
      { initials: 'TC', color: 'bg-teal-100 text-teal-800' },
    ],
    contact: '+927...',
    status: 'Approved',
    submittedDate: '2026-09-03',
    documentsCount: 3,
    hasUpdateAction: false,
  },
  {
    id: '4',
    applicationNo: 'APP-2026-0162',
    companyName: 'AL YAM...',
    fullCompanyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    reviewers: [
      { initials: '👨‍💼', color: 'bg-amber-100 text-amber-800' },
      { initials: '+3', color: 'bg-[#1B4332] text-white' },
    ],
    contact: '+927...',
    status: 'Conditional Approval',
    submittedDate: '2026-08-28',
    documentsCount: 5,
    hasUpdateAction: false,
  },
  {
    id: '5',
    applicationNo: 'APP-2026-0161',
    companyName: 'AL YAM...',
    fullCompanyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    reviewers: [
      { initials: '👨‍💼', color: 'bg-amber-100 text-amber-800' },
    ],
    contact: '+927...',
    status: 'Approved',
    submittedDate: '2026-08-28',
    documentsCount: 4,
    hasUpdateAction: false,
  },
  {
    id: '6',
    applicationNo: 'APP-2026-0159',
    companyName: 'AL YAM...',
    fullCompanyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    reviewers: [
      { initials: 'C', color: 'bg-emerald-100 text-emerald-800' },
      { initials: 'W', color: 'bg-blue-100 text-blue-800' },
      { initials: 'TC', color: 'bg-teal-100 text-teal-800' },
    ],
    contact: '9254...',
    status: 'Assessment Schedule',
    submittedDate: '2026-08-25',
    documentsCount: 3,
    hasUpdateAction: true,
  },
  {
    id: '7',
    applicationNo: 'APP-2026-0158',
    companyName: 'AL YAM...',
    fullCompanyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    reviewers: [],
    contact: '9254...',
    status: 'Approved',
    submittedDate: '2026-08-25',
    documentsCount: 4,
    hasUpdateAction: false,
  },
];

export const adminCertificates = [
  {
    id: '1',
    certificateId: 'HPDC-ESG-2026-0045',
    companyName: 'foods&drink',
    registrationNo: '5434567655555555555',
    status: 'VALID',
    issuedDate: '03 Sep 2026',
    expiryDate: '03 Sep 2027',
  },
  {
    id: '2',
    certificateId: 'HPDC-ESG-2026-0044',
    companyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    registrationNo: '987654321',
    status: 'VALID',
    issuedDate: '25 Aug 2026',
    expiryDate: '25 Aug 2031',
  },
  {
    id: '3',
    certificateId: 'HPDC-ESG-2026-0043',
    companyName: 'food factory',
    registrationNo: '98765432134567898765',
    status: 'VALID',
    issuedDate: '24 Aug 2026',
    expiryDate: '24 Aug 2027',
  },
  {
    id: '4',
    certificateId: 'HPDC-ESG-2026-0042',
    companyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    registrationNo: '987654321',
    status: 'VALID',
    issuedDate: '21 Aug 2026',
    expiryDate: '21 Aug 2028',
  },
  {
    id: '5',
    certificateId: 'HPDC-ESG-2026-0041',
    companyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    registrationNo: '987654321',
    status: 'VALID',
    issuedDate: '21 Aug 2026',
    expiryDate: '21 Aug 2031',
  },
  {
    id: '6',
    certificateId: 'HPDC-ESG-2026-0040',
    companyName: 'legal doc',
    registrationNo: '1010293847',
    status: 'VALID',
    issuedDate: '20 Aug 2026',
    expiryDate: '20 Aug 2028',
  },
  {
    id: '7',
    certificateId: 'HPDC-ESG-2026-0039',
    companyName: 'AL YAMAMAH INDUSTRIAL CO. LTD',
    registrationNo: '987654321',
    status: 'VALID',
    issuedDate: '20 Aug 2026',
    expiryDate: '20 Aug 2028',
  },
];

export const adminActivityLogs = [
  {
    id: '1',
    timestamp: '04 Sep 2026 – 01:01 PM',
    description: 'Certificate HPDC-ESG-2026-0027 viewed via public page.',
    relativeTime: 'about 2 hours ago',
  },
  {
    id: '2',
    timestamp: '04 Sep 2026 – 11:46 AM',
    description: 'Certificate HPDC-ESG-2026-0027 viewed via public page.',
    relativeTime: 'about 4 hours ago',
  },
  {
    id: '3',
    timestamp: '04 Sep 2026 – 09:58 AM',
    description: 'testing consultant commented on application APP-2026-0167.',
    relativeTime: 'about 5 hours ago',
  },
  {
    id: '4',
    timestamp: '04 Sep 2026 – 09:54 AM',
    description: 'duaafaz384@gmail.com logged out.',
    relativeTime: 'about 6 hours ago',
  },
  {
    id: '5',
    timestamp: '04 Sep 2026 – 09:15 AM',
    description: 'Certificate HPDC-ESG-2026-0017 viewed via public page.',
    relativeTime: 'about 6 hours ago',
  },
  {
    id: '6',
    timestamp: '04 Sep 2026 – 03:30 AM',
    description: 'Certificate HPDC-ESG-2026-0027 viewed via public page.',
    relativeTime: 'about 12 hours ago',
  },
  {
    id: '7',
    timestamp: '04 Sep 2026 – 02:11 AM',
    description: 'Certificate HPDC-ESG-2026-0023 viewed via public page.',
    relativeTime: 'about 13 hours ago',
  },
  {
    id: '8',
    timestamp: '04 Sep 2026 – 02:11 AM',
    description: 'Certificate HPDC-ESG-2026-0023 viewed via public page.',
    relativeTime: 'about 13 hours ago',
  },
  {
    id: '9',
    timestamp: '04 Sep 2026 – 12:51 AM',
    description: "Company food's & drink select just checking 1 year for application APP-2026-0168.",
    relativeTime: 'about 15 hours ago',
  },
  {
    id: '10',
    timestamp: '04 Sep 2026 – 12:50 AM',
    description: "Company food's & drink select just checking 1 year for application APP-2026-0168.",
    relativeTime: 'about 15 hours ago',
  },
];

export const certificateAccreditations = [
  {
    id: '1',
    name: '4 years tenure',
    duration: '1 Year',
    applicationFee: 'SAR 200',
    certificateFee: 'SAR 1,500',
    status: 'Inactive',
  },
  {
    id: '2',
    name: 'just checking',
    duration: '1 Year',
    applicationFee: 'SAR 12,345',
    certificateFee: 'SAR 12,345',
    status: 'Active',
  },
  {
    id: '3',
    name: 'ESG-CERTIFICATE-A',
    duration: '5 Years',
    applicationFee: 'SAR 34,345',
    certificateFee: 'SAR 54,555',
    status: 'Active',
  },
  {
    id: '4',
    name: 'esg certificat a',
    duration: '2 Years',
    applicationFee: 'SAR 12,345',
    certificateFee: 'SAR 99,999',
    status: 'Active',
  },
  {
    id: '5',
    name: 'ESG-CERTIFICATE-A',
    duration: '2 Years',
    applicationFee: 'SAR 65,654',
    certificateFee: 'SAR 54,656',
    status: 'Active',
  },
];
