'use client';
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  English: {
    dashboard: 'Dashboard',
    allApplications: 'All Applications',
    myCertificates: 'My Certificates',
    signOut: 'Sign Out',
    applyForCertifications: 'Apply for Certifications',
    hpdcPlatform: 'HPDC ESG Certificate Platform',
    applicationManagement: 'Application Management',
    esgTayibPortal: 'ESG Tayib Sustainability Certification Portal',
    totalApplications: 'Total Applications',
    rejectedApplications: 'Rejected Applications',
    activeCertificates: 'Active Certificates',
    suspendedCertificates: 'Suspended Certificates',
    withdrawnCertificates: 'Withdrawn Certificates',
    expiredCertificates: 'Expired Certificates',
    recentApplications: 'Recent Applications',
    searchPlaceholder: 'Search...',
    searchApplications: 'Search applications...',
    search: 'Search...',
    allCertificates: 'All Certificates',
    allStatus: 'All status',
    applicationNo: 'Application No.',
    company: 'Company',
    status: 'Status',
    submitted: 'Submitted',
    documents: 'Documents',
    action: 'Action',
    viewDocuments: 'View Documents',
    viewDetails: 'View Details',
    certificateId: 'Certificate ID',
    certificateType: 'Certificate Type',
    issued: 'Issued',
    expiry: 'Expiry',
    sites: 'Sites',
    viewFullCertificate: 'View Full Certificate',
    showing: 'Showing',
    of: 'of',
    bookingPerPage: 'Booking Per Page',
    companyDetails: 'Company Details',
    companyDetailsSubtitle: 'Complete the company information to proceed with your ESG certification application',
    orgBasicDetails: 'Organization Basic Details',
    legalNameEn: 'Legal Company Name (English)',
    legalNameAr: 'Legal Company Name (Arabic)',
    crNumber: 'Company Registration Number (CR)',
    vatYear: 'VAT / Tax Registration Year',
    orgType: 'Type of Organization',
    sector: 'Industry / Sector',
    addressContactDetails: 'Address and Contact Details',
    headOfficeEn: 'Head Office Address (English)',
    headOfficeAr: 'Head Office Address (Arabic)',
    website: 'Website Address',
    websiteAr: 'Website Address (Arabic)',
    contactInfo: 'Contact Information',
    legalDocs: 'Legal Documents',
    crDocument: 'Company Registration Number CR Document',
    vatDocument: 'VAT / Tax Registration Document',
    mroDocument: 'Factory / Premises MRO Document',
    moaDocument: 'MoA Document',
    scopeMultisite: 'Scope and Multisite Configuration',
    certAreasEn: 'Areas of Certification (English)',
    certScopeAr: 'Scope of Certification (Arabic)',
    multisiteQuestion: 'Does your organization operate across multiple sites?',
    workforceDetails: 'Workforce Details',
    totalEmployees: 'Total Number of Employees',
    permanentEmployees: 'Permanent Employees',
    contractEmployees: 'Contract Employees',
    numberOfSites: 'Number of Sites',
    shiftOperations: 'Shift Operations',
    remoteWork: 'Remote Work',
    brandDetails: 'Brand Details',
    addBrand: 'Add New Brand',
    certComplianceStatus: 'Certification and Compliance Status',
    otherCerts: 'Other Certificates',
    esgPracticeDetails: 'ESG and Sustainability Practice Details',
    additionalNotes: 'Additional Notes',
    supportingDocs: 'Supporting Documents',
    dragDropText: 'Drag and drop files here or click to browse',
    esgSurvey: 'ESG Assessment Survey',
    surveySubtitle: 'Answer these questions to complete the application form',
    section1Of4: 'Section 1 of 4',
    section2Of4: 'Section 2 of 4',
    section3Of4: 'Section 3 of 4',
    section4Of4: 'Section 4 of 4',
    esgAssessment: 'ESG Assessment',
    indicatesRequired: '* Indicates Required Questions',
    allChangesSaved: 'All changes saved',
    yes: 'Yes',
    partial: 'Partial',
    no: 'No',
    next: 'Next',
    back: 'Back',
    clearForm: 'Clear form',
    markFillLater: 'Mark Fill later',
    profileInformation: 'Profile Information',
    changePassword: 'Change Password',
    notifications: 'Notifications',
    fillRequiredFieldsWarning: 'Please fill in all required fields marked with an asterisk (*) before proceeding.',
    Valid: 'Valid',
    Suspended: 'Suspend',
    Withdrawn: 'Withdrawn',
    Expired: 'Expired'
  },
  Arabic: {
    dashboard: 'لوحة التحكم',
    allApplications: 'جميع الطلبات',
    myCertificates: 'شهاداتي',
    signOut: 'تسجيل الخروج',
    applyForCertifications: 'التقدم بطلب للحصول على الشهادة',
    hpdcPlatform: 'منصة شهادات ESG الخاصة بـ HPDC',
    applicationManagement: 'إدارة الطلبات',
    esgTayibPortal: 'بوابة شهادات الاستدامة ESG طيب',
    totalApplications: 'إجمالي الطلبات',
    rejectedApplications: 'الطلبات المرفوضة',
    activeCertificates: 'الشهادات النشطة',
    suspendedCertificates: 'الشهادات المعلقة',
    withdrawnCertificates: 'الشهادات المسحوبة',
    expiredCertificates: 'الشهادات المنتهية',
    recentApplications: 'الطلبات الأخيرة',
    searchPlaceholder: 'بحث...',
    searchApplications: 'البحث في الطلبات...',
    search: 'بحث...',
    allCertificates: 'جميع الشهادات',
    allStatus: 'جميع الحالات',
    applicationNo: 'رقم الطلب',
    company: 'الشركة',
    status: 'الحالة',
    submitted: 'تاريخ التقديم',
    documents: 'المستندات',
    action: 'الإجراء',
    viewDocuments: 'عرض المستندات',
    viewDetails: 'عرض التفاصيل',
    certificateId: 'معرف الشهادة',
    certificateType: 'نوع الشهادة',
    issued: 'تاريخ الإصدار',
    expiry: 'تاريخ الانتهاء',
    sites: 'المواقع',
    viewFullCertificate: 'عرض الشهادة الكاملة',
    showing: 'عرض',
    of: 'من',
    bookingPerPage: 'العناصر في الصفحة',
    companyDetails: 'تفاصيل الشركة',
    companyDetailsSubtitle: 'أكمل معلومات الشركة للمتابعة في طلب الحصول على شهادة ESG الخاصة بك',
    orgBasicDetails: 'البيانات الأساسية للمنشأة',
    legalNameEn: 'اسم الشركة الرسمي (بالإنجليزي)',
    legalNameAr: 'اسم الشركة الرسمي (بالعربي)',
    crNumber: 'رقم السجل التجاري (CR)',
    vatYear: 'سنة التسجيل في ضريبة القيمة المضافة / الضريبة',
    orgType: 'نوع المنشأة',
    sector: 'القطاع / الصناعة',
    addressContactDetails: 'تفاصيل العنوان والاتصال',
    headOfficeEn: 'عنوان المقر الرئيسي (بالإنجليزي)',
    headOfficeAr: 'عنوان المقر الرئيسي (بالعربي)',
    website: 'عنوان الموقع الإلكتروني',
    websiteAr: 'عنوان الموقع الإلكتروني (بالعربي)',
    contactInfo: 'معلومات الاتصال',
    legalDocs: 'المستندات القانونية',
    crDocument: 'وثيقة السجل التجاري',
    vatDocument: 'وثيقة التسجيل الضريبي',
    mroDocument: 'وثيقة تشغيل المصنع / الموقع MRO',
    moaDocument: 'عقد التأسيس MoA',
    scopeMultisite: 'نطاق وتعدد المواقع',
    certAreasEn: 'مجالات الحصول على الشهادة (بالإنجليزي)',
    certScopeAr: 'نطاق الشهادة (بالعربي)',
    multisiteQuestion: 'هل تعمل منشأتك عبر مواقع متعددة؟',
    workforceDetails: 'تفاصيل القوى العاملة',
    totalEmployees: 'إجمالي عدد الموظفين',
    permanentEmployees: 'الموظفون الدائمون',
    contractEmployees: 'الموظفون المتعاقدون',
    numberOfSites: 'عدد المواقع',
    shiftOperations: 'عمليات الورديات',
    remoteWork: 'العمل عن بُعد',
    brandDetails: 'تفاصيل العلامات التجارية',
    addBrand: 'إضافة علامة تجارية جديدة',
    certComplianceStatus: 'حالة الشهادات والامتثال',
    otherCerts: 'شهادات أخرى',
    esgPracticeDetails: 'تفاصيل ممارسات ESG والاستدامة',
    additionalNotes: 'ملاحظات إضافية',
    supportingDocs: 'المستندات الداعمة',
    dragDropText: 'اسحب الملفات وأفلتها هنا أو انقر للتصفح',
    esgSurvey: 'استبيان تقييم ESG',
    surveySubtitle: 'أجب عن هذه الأسئلة لإكمال نموذج الطلب',
    section1Of4: 'القسم 1 من 4',
    section2Of4: 'القسم 2 من 4',
    section3Of4: 'القسم 3 من 4',
    section4Of4: 'القسم 4 من 4',
    esgAssessment: 'تقييم ESG',
    indicatesRequired: '* يشير إلى الأسئلة المطلوبة',
    allChangesSaved: 'تم حفظ جميع التغييرات',
    yes: 'نعم',
    partial: 'جزئي',
    no: 'لا',
    next: 'التالي',
    back: 'السابق',
    clearForm: 'مسح النموذج',
    markFillLater: 'تعبئة لاحقاً',
    profileInformation: 'معلومات الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    notifications: 'الإشعارات',
    fillRequiredFieldsWarning: 'يرجى ملء جميع الحقول المطلوبة المميزة بنجمة (*) قبل المتابعة.',
    Valid: 'صالِح',
    Suspended: 'تجميد',
    Withdrawn: 'مَسْحوب',
    Expired: 'منتهي'
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('English');

  const t = (key) => {
    return translations[language]?.[key] || translations.English[key] || key;
  };

  const isRtl = language === 'Arabic';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      <div dir={isRtl ? 'rtl' : 'ltr'} className={isRtl ? 'font-sans' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'English',
      setLanguage: () => { },
      t: (key) => key,
      isRtl: false,
    };
  }
  return context;
}
